version: '3'

services:
  ui:
    image: bjornmagnusson/pi-ui
    build:
      context: .
      dockerfile: Dockerfile.ng
    ports:
      - "80:80"
    environment:
      - API_HOST=192.168.0.105
      - API_PORT=8080
    deploy:
      placement:
        constraints:
          - node.hostname == pi3
