version: '2.4'

services:
  ui:
    image: bjornmagnusson/pi-ui:${TAG:-latest}
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:3000"
    environment:
      - API_HOST=192.168.0.107
      - API_PORT=8080
