version: 2
jobs:
  build:
    docker:
      - image: docker:stable-git
    steps:
      - checkout
      - run:
          name: Install Docker Compose
          command: |
            wget -P /tmp https://github.com/docker/compose/releases/download/1.20.1/docker-compose-`uname -s`-`uname -m`
            sudo mv /tmp/docker-compose* /usr/local/bin/docker-compose
            sudo chmod +x /usr/local/bin/docker-compose          
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: |
            docker run --rm --privileged multiarch/qemu-user-static:register --reset
            docker-compose build
            if [[ ! -z "${CIRCLE_TAG}" ]]; then
              TAG=${CIRCLE_TAG} docker-compose build
            fi
      - deploy:
          name: Push Docker image to Docker Hub
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              docker login -u $DOCKER_USER -p $DOCKER_PASS
              docker-compose -f docker-compose.dev.yml push
            fi
            if [[ ! -z "${CIRCLE_TAG}" ]]; then
              docker login -u $DOCKER_USER -p $DOCKER_PASS
              TAG=${CIRCLE_TAG} docker-compose -f docker-compose.dev.yml push
            fi
