version: 2
jobs:
  build:
    docker:
      - image: docker:stable-git
    steps:
      - checkout
      - setup_remote_docker:
          version: 18.05.0-ce
      - run:
          name: Build and push Docker image
          command: |
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker build --target test .
            docker build -t bjornmagnusson/pi-ui:${CIRCLE_SHA1} .
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              docker image build -t bjornmagnusson/pi-ui:canary .
            fi
            if [[ ! -z "${CIRCLE_TAG}" ]]; then
              docker image build -t bjornmagnusson/pi-ui:${CIRCLE_TAG} .
            fi
            docker push bjornmagnusson/pi-ui
workflows:
  version: 2
  build:
    jobs:
      - build:
          context: DOCKER_HUB
